export const KICK_STREAMERS: { username: string; tags: string[]; character: string }[] = [
  { username: 'SXB', tags: ['CIA', 'CIA Leaders', 'DO Commander', 'DO'], character: 'Abdulsamad Alqurashi' },
  { username: 'https://kick.com/ysmo', tags: ['CIA', 'CIA Deputy', 'CIA Leaders'], character: 'Agent X' },
  { username: 'Osamah', tags: ['CIA', 'CIA Director'], character: 'Alexander Mahon' },
  { username: 'MOLO101', tags: ['CIA', 'CIA Leaders', 'CIA Doctor', 'DS Commander', 'DS'], character: 'Dr.Anderw' },
  { username: 'lMeshari4', tags: ['CIA', 'CIA Leaders', 'DA Commander'], character: 'Michael Conner' },
  { username: 'tmnaa', tags: ['CIA', 'DO Deputy'], character: 'Abdullah Alshmmari' },
  { username: 'RpWy', tags: ['CIA', 'DO'], character: 'Abdullah Khalid' },
  { username: 'TelleR_76', tags: ['CIA', 'CIA Leaders'], character: 'Teller "Agent-Omega"' },
  { username: 'oFlag', tags: ['CIA', 'CIA Doctors'], character: 'Dexter Morgan' },
  { username: 'AbuSwe7l', tags: ['CIA', 'ALPHA Son'], character: 'Rick Mahon' },
  { username: 'IC4C', tags: ['Respect', 'CIA', 'CIA Leaders'], character: 'Saif Alansary' },
  { username: 'Ab2dy', tags: ['CIA', 'DO'], character: 'Abdullah Abd Al-Aziz' },
  { username: 'brof2', tags: ['CIA', 'CIA Doctor', 'DO'], character: 'Brof' },
  { username: 'IB6h', tags: ['Respect', 'CIA', 'CIA Leaders', 'Executive Director'], character: 'Damien Silver Beta' },
  { username: 'PROMT3B', tags: ['CIA', 'Death Battelion Deputy'], character: 'DON' },
  { username: 'Fahad', tags: ['CIA', 'DO'], character: 'Fahad Saad' },
  { username: 'Muvxn', tags: ['CIA', 'CIA Pilots', 'DO'], character: 'Musab Al Sultan' },
  { username: 'CKIV', tags: ['CIA', 'Border Breaking Battalion', 'DO'], character: 'Frank Peter | Agro' },
  { username: 'Azeez', tags: ['CIA', 'CIA Leaders', 'Flight Field Commander'], character: 'Eziar Qab' },
  { username: 'xEid', tags: ['CIA', 'CIA Leaders','Death Battelion Commanders', 'DO'], character: 'Bob Marley | Rambo' },
  { username: 'Firas', tags: ['CIA', 'DO'], character: 'Snop Marley' },
  { username: '7omah', tags: ['CIA', 'CIA Leaders', 'CIA Pilots', 'DI Deputy'], character: 'Murph' },
  { username: 'Zeeyadx', tags: ['CIA', 'DO', 'SOG Commanders'], character: 'Agent Hunter' },
  { username: 'xlxwi', tags: ['CIA', 'DO'], character: 'Ali Abdullah' },
  { username: 'Dark12', tags: ['CIA', 'DA'], character: 'Alex Michael' },
  { username: 'kawd10', tags: ['CIA', 'DA Deputy'], character: 'Martin Peterson' },
  { username: 'Vilon', tags: ['CIA', 'DO', 'SOG Commanders'], character: 'Agent Silver Bullet' },
  { username: '7soo', tags: ['CIA', 'Border Breaking Battalion Leader'], character: 'Paul' },
  { username: 'LiRx', tags: ['CIA', 'Border Breaking Battalion Deputy'], character: 'Marcus' },
  { username: 'iikhd7', tags: ['CIA', 'Border Breaking Battalion'], character: 'Billy' },
  { username: 'Jntel', tags: ['CIA', 'Border Breaking Battalion'], character: 'Tango' },
  { username: 's6mito', tags: ['CIA', 'DO'], character: 'Satam Al Otaibi' },
  { username: 'vSaleh', tags: ['CIA', 'DO'], character: 'Saleh Alenzi "Agent-Ninja"' },
  { username: 'INQ', tags: ['CIA', 'CIA Leaders'], character: 'James Arthur' },
  { username: 'mesh7', tags: ['CIA', 'DO'], character: 'Meshal Salman' },
  { username: 'Sult', tags: ['CIA', 'CIA Leaders', 'DO', 'SOG Commanders'], character: 'Sulatn Alotaibi | Zolo' },
  { username: 'itsOG', tags: ['Agent'], character: 'Talq AlSbi3i' },
  { username: 'MTNEWS', tags: ['Intelligencer'], character: '3amar Bin Abdulhamid' },
  { username: 'xMusaad', tags: ['Agent'], character: 'Musa3d' },
  { username: '1RWi', tags: ['CIA', 'Death Battelion Deputy Commanders'], character: 'Ms.Caplin' },
  { username: 'odn35', tags: ['CIA', 'CIA Doctor', 'DS Deputy', 'DS'], character: 'Benny Surge "Agent-Gaster"' },
  { username: 'VMalik', tags: ['CIA', 'DS'], character: 'Munir Almalky' },
  { username: 'iABS', tags: ['CIA', 'Border Breaking Battalion'], character: 'Aba Alhareth' },
  { username: 'abu_saad3', tags: ['CIA', 'DS'], character: 'Ali Bin Saad' },
  { username: 'cRaed', tags: ['CIA', 'DS'], character: 'Wiliam Coby' },
  { username: '71sky', tags: ['CIA', 'DS'], character: 'Skylar Scott' },
  { username: 'sniperxzaid', tags: ['CIA', 'DS'], character: 'Zaid Muhammad' },
  { username: '0xsultan', tags: ['CIA', 'DS'], character: 'Lysander Restova' },
  { username: 'tqrolld', tags: ['CIA', 'DS'], character: 'Victor Rundn' },
  { username: 'Fwaz', tags: ['CIA', 'CIA Leaders', 'DOU Commander'], character: 'Fwaz Jnaza' },
  { username: 'D7MX', tags: ['CIA', 'CIA Leaders', 'Executive Director'], character: 'Echo' },
  { username: 'Abdullahx', tags: ['CIA', 'CIA Leaders', 'CIA Deputy'], character: 'Bravo' },
  { username: 'Twlf', tags: ['CIA', 'SOG', 'Trainer'], character: 'Abdullah Alharbi' },
  { username: 'XKHD', tags: ['CIA', 'SOG', 'Trainer'], character: 'Khalid Fraij' },
  { username: 'Mo7aGame', tags: ['CIA', 'SOG', 'Trainer'], character: 'Qais Alkaser' },
  { username: 'Chamander', tags: ['CIA', 'SOG', 'Trainer'], character: 'Chamander Smith' },
  { username: 'hnodyy', tags: ['CIA', 'SOG', 'Trainer'], character: 'Muhanned Abdullah' },
  { username: 'Hko0o', tags: ['CIA', 'SOG', 'Trainer'], character: 'Maan Albaqmi' },
  { username: 'Nawaf1023', tags: ['CIA', 'SOG', 'Trainer'], character: 'Sarhan Aldossri' },
  { username: 'crezy24', tags: ['CIA', 'SOG', 'Trainer'], character: 'Abdulaziz Fahad' },
  { username: 'abdlatef1', tags: ['CIA', 'SOG', 'Trainer'], character: 'Abdlatef Alanazi' },
  { username: 'kingback23', tags: ['CIA', 'SOG', 'Trainer'], character: 'Ammar Adil' },
  { username: 'vbaz', tags: ['CIA', 'SOG', 'Trainer'], character: 'Baz Stark' },
  { username: '4speed', tags: ['CIA', 'SOG', 'Trainer'], character: 'Ahmed Alsbammedi' },
];

export const POLLING_INTERVAL_SECONDS: number = 90;

export const ENABLE_APPLY_SECTION = false;

export const ENABLE_SHARE_STREAM_VIEW = false;